Repository AshciR/group-chat-digest, pull requests merged in 2024-05, with the labels that each got.

#37 Issue 35
  README.md
  docker-compose.yml
  requirements.txt
  src/__pycache__/message_storage.cpython-311.pyc
  src/__pycache__/openai_utils.cpython-311.pyc
  src/data_classes.py
  src/message_storage.py
  src/telegram_bot.py
Labels: enhancement

#38 Issue 25
  Dockerfile
  README.md
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  requirements.txt
Labels: refactor

#40 Issue 12 - Pt.1
  .gitignore
  Dockerfile
  README.md
  pyproject.toml
  requirements-dev.lock
  src/__pycache__/message_storage.cpython-311.pyc
  src/__pycache__/openai_utils.cpython-311.pyc
  src/chat_nuff_bot/__init__.py
  src/chat_nuff_bot/message_storage.py
  src/chat_nuff_bot/openai_utils.py
  src/chat_nuff_bot/telegram_bot.py
  tests/openai-test.py
  tests/test_chat_nuff_bot/__init__.py
  tests/test_chat_nuff_bot/test_message_storage.py
Labels: enhancement

#43 Using uv for build tool instead of pip
  Dockerfile
  docker-compose.yml
  src/message_storage.py
Labels: refactor

#49 complete white list issue
  src/telegram_bot.py
  src/white_list.py
Labels: enhancement

#50 Add webserver for health checks
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/main.py
  src/server.py
  src/telegram_bot.py
Labels: enhancement

#52 Issue 51
  .gitignore
  Dockerfile
Labels: infrastructure

#53 Issue 48
  pyproject.toml
  requirements-dev.lock
  src/openai_utils.py
  src/telegram_bot.py
  tests/test_telegram_bot.py
Labels: enhancement

#54 Update some of the logs
  src/message_storage.py
  src/telegram_bot.py
Labels: refactor

#55 Fix whitelist for Gerousia
  src/white_list.py
Labels: bug

#61 Add girls to whitelist
  src/white_list.py
Labels: enhancement

#63 Issue 57
  .gitignore
  src/main.py
  src/message_storage.py
  tests/test_message_storage.py
Labels: bug

#64 Spike 62
  src/main.py
  src/telegram_bot.py
  src/white_list.py
  tests/test_telegram_bot.py
Labels: enhancement

#66 Add constant for commands
  src/main.py
  src/telegram_bot.py
Labels: bug
